name: .NET Core CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  

    - name: Restaurar las dependencias
      run: dotnet restore "Api.sln" 

    - name: Compilar el proyecto
      run: dotnet build "Api.sln" --configuration Release --no-restore

    - name: Ejecutar los Tests
      run: dotnet test "Api.sln" --no-restore --verbosity normal

    - name: Publicar la aplicación
      run: dotnet publish "Api.csproj" --configuration Release --output ./Publish --self-contained true --runtime linux-x64 --verbosity detailed

    - name: Desplegar
      run: |
        echo "Acá se ejecutaría el deploy."
