name: .NET Core CI/CD

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configurar .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'  

    - name: Restauran las dependencias
      run: dotnet restore "Api.sln" 

    - name: Compila el proyecto
      run: dotnet build "Api.sln" --configuration Release --no-restore

    - name: Ejecutan los Test
      run: dotnet test "Api.sln" --no-restore --verbosity normal

    - name: Se arma el Publish
      run: dotnet publish "Api.csproj" --configuration Release --output ./Publish

    - name: Deploy
      run: |
        echo "Acá se ejecutaria el deploy."
